### PR TITLE
Add basic commands to navigate between cells

### PR DESCRIPTION
**Pull request by Klafyvel**
This adds three commands to teach slime how to navigate between cells.

### CODE REVIEW

**Comment by jpalardy** [comment]
Hi @Klafyvel 

I'm unclear as to how much use this cell feature is getting… 🤔 

Since it lives "on top" of vim-slime, it makes me wonder if it could be a separate plugin.

What do you think?

**Comment by Klafyvel** [comment]
Hi,
Although the cell feature is what drove me to vim-slime, it's true that it
feels a bit like an addon on top of slime.

I'm perfectly fine with making my own plugin for this feature, especially
since I have some other ideas to improve it. 🙂


Le mar. 28 déc. 2021 à 06:30, Jonathan Palardy ***@***.***> a
écrit :

**Comment by Klafyvel** [comment]
Here is the plugin for future reference (and self-promotion :innocent: ) : https://github.com/Klafyvel/vim-slime-cells

**Comment by jpalardy** [comment]
If you feel it's ready (or when you do), let's open a PR to link to it

At that point, we might consider stripping out any cell code from vim-slime and delegate 🤔

**Pull request closed without merging**
