### PR TITLE
Deal with newline, etc

### PR DESCRIPTION
**Pull request by jpalardy**
Credits to @randomizedthinking with minor fix (`elseif` -> `else` on line 78)

### CODE REVIEW

**Comment by jpalardy** [comment]
@oblitum let me know how this PR works for you, or if I missed anything

**Comment by oblitum** [comment]
Actually not quite, behavior for #205 under pgcli is better than this one (#206), even though this one doesn't produce bad indentation like

```
analysis> CREATE TABLE number_data_types (
     numeric_column numeric(20,5),
         real_column real,
             double_column double precision
             );
```

For this example:

```sql
SELECT sum(pls14.visits) AS visits_2014,
       sum(pls09.visits) AS visits_2009
FROM pls_fy2014_pupld14a pls14 JOIN pls_fy2009_pupld09a pls09
ON pls14.fscskey = pls09.fscskey
WHERE pls14.visits >= 0 AND pls09.visits >= 0;
```

I get this with this pull:

```
analysis> SELECT sum(pls14.visits) AS visits_2014,
        sum(pls09.visits) AS visits_2009
        FROM pls_fy2014_pupld14a pls14 JOIN pls_fy2009_pupld09a pls09
        ON pls14.fscskey = pls09.fscskey
        WHERE pls14.visits >= 0 AND pls09.visits >= 0;
```

While with #205 I get this:

```
analysis> SELECT sum(pls14.visits) AS visits_2014,
        sum(pls09.visits) AS visits_2009
 FROM pls_fy2014_pupld14a pls14 JOIN pls_fy2009_pupld09a pls09
 ON pls14.fscskey = pls09.fscskey
 WHERE pls14.visits >= 0 AND pls09.visits >= 0;
```

Which looks to resemble better the original text.

**Comment by oblitum** [comment]
I think the route is actually fixing #205 by removing the `\n` there. I'm taking a look how to do it.

**Comment by oblitum** [comment]
Ah, my bad, sorry! xD I didn't pulled this pull yet. Doing it now.

**Comment by oblitum** [comment]
False alarm! It's working fine :P :+1:

**Comment by jpalardy** [comment]
awesome!

let's merge for now, please let me know if it's misbehaving

**Comment by oblitum** [comment]
oh, I had one suggestion before the merge, and it seems to work, it's to replace the ctrl sequence `^M` for `\<cr>`.

**Comment by oblitum** [comment]
AFAICT, when doing that, I'm not noticing difference in behavior.

**Comment by jpalardy** [comment]
merged in #207

**Pull request merged**
