### PR TITLE
Add note about zero-indexing in tmux windows

### PR DESCRIPTION
**Pull request by sursh**
This took me a little trial and error to figure out, especially because vim-slime hangs without an error message if you enter an invalid value.

### CODE REVIEW

**Comment by sursh** [comment]
Related: in the same section, I have no idea what this sentence refers to: `This is what you put in the -L flag`. Perhaps it's a reference to something upstream that changed?

**Comment by jpalardy** [comment]
Hi there,

Sorry about the confusion… The whole configuration text could be re-worked. It's a struggle to explain what vim-slime does and what (configuration) parts belong to tmux. I'm open to suggestions to clarify things.

For example, the part about `This is what you put in the -L flag` refers to the `-L` flag you could pass tmux if you invoked it, yourself, from the command-line.

**Comment by jpalardy** [comment]
I do appreciate the PR though :-)

If you think you can un-muddle things even more, I'll be able to merge some more.

**Comment by sursh** [comment]
Ah, I see. I'm reworking that sentence. Don't be too hard on yourself, I thought the installation directions were pretty clear!

**Pull request merged**
