### PR TITLE
Removed conditions for Haskell indentation

### LINKED ISSUE #67: Lines after the first are not indented when "let" is added (Haskell)
```hs
item :: Parser Char
item = Parser (\s -> case s of
    "" -> []
    c:cs -> [(c,cs)])
```
When sending the above to `tmux`, the following error occurs:

```hs
Prelude> :{
Prelude| let item :: Parser Char
Prelude|     item = Parser (\s -> case s of
Prelude|     "" -> []
Prelude|     c:cs -> [(c,cs)])
Prelude| :}

<interactive>:5:5:
    parse error (possibly incorrect indentation or mismatched brackets)
```
The problem is that only the first line is indented when `let` is added.

I took a look at the source and it seems that lines beginning with whitespace are [deliberately not indented](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/haskell/slime.vim#L40). May I ask why this is done? Should I be indenting my code in a different way?

### PR DESCRIPTION
**Pull request by dariusf**
Fixes #67

### CODE REVIEW

**Comment by jpalardy** [comment]
Looking good, thanks :-)

**Comment by dariusf** [comment]
I think you may have forgotten to merge this. :)

**Comment by jpalardy** [comment]
Wrong button … :-/

**Comment by dariusf** [comment]
Thanks!

**Pull request merged**
